### ISSUE TITLE
Request for Advice on Processing Large-Scale Sequential Image Data

### ISSUE THREAD

**Issue by takafire2222** [xuelunshen/gim#28]
Dear Developer,

I hope this message finds you well.

We are currently working with sequential image data consisting of over 1000 images, similar to those captured by drones. In processing such large-scale datasets, we have encountered several challenges. In light of this, we would greatly appreciate your expert insights on the following:

1. Are there any best practices for handling such large sequential datasets (1000+ images) in the context of 3D reconstruction? Additionally, are there any parameters or configurations we should adjust when working with this type of data compared to more general datasets?

2. Do you have any recommended specific strategies or modifications to the existing code for dealing with extensive sequential data?

Any ideas you could share on adapting the current system to handle larger, sequential datasets would be immensely helpful.

Thank you in advance for your time and expertise.

Best regards,

**Comment by xuelunshen** [comment]
Because I was on vacation last week, so this reply came a little late. Please forgive me. 

If you use 3D Reconstruction released by GIM to take 1000+ images, I strongly recommend that you modify the sampling logic of the reconstructed image pair, which is here:https://github.com/xuelunshen/gim/blob/e06dba6c939ea5f4be8a11071df771d1956d3fcb/reconstruction.py#L43 https://github.com/xuelunshen/gim/blob/e06dba6c939ea5f4be8a11071df771d1956d3fcb/hloc/pairs_from_exhaustive.py#L55-L56 If these two lines of comment are canceled, the code will combine 5 adjacent images for reconstruction, rather than reconstructing 1000+ images in pairs.

Because for reconstruction, it makes sense to match only images with overlapping areas. When your drone flies far away, an image does not need to be matched with images that are far away because they do not have overlapping areas on pixels.

**Comment by xuelunshen** [comment]
As you mentioned, incremental reconstruction on an already reconstructed scene can refer to the approach in `pipeline_loftr.py` from hloc. My suggestion is to reconstruct on the image pairs that have overlapping. You can use image retrieval methods to find the overlapping image pairs and then proceed with incremental reconstruction.
